# Generated by Django 4.2.4 on 2023-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Sobrenome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
