# Generated by Django 4.2.7 on 2023-11-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_cpf_cliente_cpf_rename_nome_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
