# Generated by Django 4.2.7 on 2023-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Logradouro',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
