# Generated by Django 4.2.7 on 2023-11-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_numero_alter_cliente_logradouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
