# Generated by Django 4.2.7 on 2023-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_remove_cliente_numero_alter_cliente_logradouro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Numero',
            field=models.CharField(default='Sem Numero', max_length=10),
        ),
    ]
