# Generated by Django 4.2.7 on 2023-11-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_cliente_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Numero',
        ),
    ]
