# Generated by Django 4.2.7 on 2023-11-14 14:45

import cliente.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_remove_cliente_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter apenas números.'), cliente.models.valida_CPF]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Contato',
            field=models.CharField(max_length=50, null=True, validators=[cliente.models.valida_contato]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Logradouro',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
