# Generated by Django 4.2.4 on 2023-11-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_cliente_cpf_alter_cliente_contato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Contato',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Logradouro',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nome',
            new_name='nome',
        ),
    ]
