# Generated by Django 4.2.7 on 2023-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.AddField(
            model_name='livro',
            name='Codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='livro',
            name='Editora',
            field=models.CharField(default='', max_length=50),
        ),
    ]
