# Generated by Django 4.2.7 on 2023-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_rename_nome_livro_nome_livro_codigo_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Ano',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='livro',
            name='Edição',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='livro',
            name='Idioma',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('de', 'Alemão'), ('it', 'Italiano'), ('ja', 'Japonês'), ('zh', 'Chinês (Mandarim)'), ('ko', 'Coreano'), ('ru', 'Russo'), ('ar', 'Árabe'), ('hi', 'Hindi'), ('sw', 'Suaíli'), ('tr', 'Turco'), ('nl', 'Holandês')], default='pt', max_length=2),
        ),
    ]
