# Generated by Django 4.2.7 on 2023-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livro_ano_livro_edição_livro_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Quantidade',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Ano',
            field=models.DateField(),
        ),
    ]
