# Generated by Django 4.2.7 on 2023-11-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_livro_quantidade_alter_livro_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='Ano',
            new_name='Publicação',
        ),
        migrations.AlterField(
            model_name='livro',
            name='Quantidade',
            field=models.IntegerField(),
        ),
    ]
