# Generated by Django 4.2.7 on 2023-11-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livro_nome_alter_livro_publicação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='Nome',
            field=models.CharField(max_length=50),
        ),
    ]
