# Generated by Django 4.2.4 on 2023-11-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livro_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='Codigo',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Edição',
            new_name='edicao',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Editora',
            new_name='editora',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Idioma',
            new_name='idioma',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Publicação',
            new_name='publicacao',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Quantidade',
            new_name='quantidade',
        ),
    ]
