# Generated by Django 4.2.7 on 2023-11-18 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateField(default=datetime.date(2023, 12, 2)),
        ),
    ]
