# Generated by Django 4.2.7 on 2023-11-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0004_remove_emprestimo_devolvido_emprestimo_devolucao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='devolucao',
            new_name='devolução',
        ),
    ]
