# Generated by Django 4.2.4 on 2023-11-28 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_rename_devolucao_emprestimo_devolução'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolução',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateField(default=datetime.date(2023, 12, 12)),
        ),
    ]
